const $=s=>document.querySelector(s);let step=0,answers,plan,measured='';const token=new URLSearchParams(location.hash.slice(1)).get('acceso');if(token){sessionStorage.setItem('santicorrea-demo-access',token);history.replaceState(null,'',location.pathname+location.search)}
const access=sessionStorage.getItem('santicorrea-demo-access')||'';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
function showStep(){document.querySelectorAll('.step').forEach((e,i)=>e.hidden=i!==step);$('#step-label').textContent=`${step+1} de 5`;$('#progress').value=step+1;$('#prev').hidden=step===0;$('#next').textContent=step===4?'Preparar mi plan':'Siguiente';$('#error').textContent=''}showStep();
function read(){return {task:$('#task').value.trim(),process:$('#process').value.trim(),minutes:Number($('#hours').value)*60+Number($('#minutes').value),approx:$('#approx').checked,count:Number($('#count').value),period:$('#period').value,review:$('#review').value.trim()}}
function validTime(h,m){return h.value!==''&&m.value!==''&&Number.isInteger(+h.value)&&+h.value>=0&&+h.value<=10000&&Number.isInteger(+m.value)&&+m.value>=0&&+m.value<=59}
function validate(){const a=read();if(step===0&&a.task.length<10)return 'Describe tu tarea con al menos diez caracteres.';if(step===1&&a.process.length<10)return 'Cuenta un poco más de tu proceso.';if(step===2&&(!validTime($('#hours'),$('#minutes'))||a.minutes<=0))return 'Introduce un tiempo mayor que cero, con minutos entre 0 y 59.';if(step===3&&(!Number.isInteger(a.count)||a.count<1||a.count>10000))return 'Introduce una frecuencia válida, de una vez o más.';if(step===4&&a.review.length<10)return 'Indica qué parte te cuesta y qué debes revisar.';return ''}
function localPlan(a){return {summary:a.task,steps:['Describe el formato de la entrega y reúne las fuentes que ya utilizas.','Entrega a la IA un ejemplo sin datos privados y pide un borrador basado únicamente en esas fuentes.','Compara el borrador con las fuentes y completa lo que falte antes de entregar.'],review:'Usa tu criterio en esta parte: '+a.review,test:'Prueba una entrega comparable con el proceso actual. Cronometra preparación, correcciones y revisión final. Registra el total aquí.',assumptions:['Este es un plan guiado general; no ha analizado tus herramientas con un modelo de IA.','El ahorro depende de la calidad de las fuentes y del tiempo necesario para revisar. No se asigna un tiempo futuro sin una prueba.']}}
async function enrich(a){const res=await fetch('https://santicorrea-contenido-api.vercel.app/api/procesos',{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Access':access},body:JSON.stringify(a),signal:AbortSignal.timeout(100000)});let d;try{d=await res.json()}catch{throw Error('La conexión con IA no respondió.')}if(!res.ok)throw Error(d.error||'No se pudo generar el plan.');return d}
function format(n){return `${Math.floor(n/60)} h ${Math.round(n%60)} min`}
function render(mode){$('#input-panel').hidden=true;$('#result-panel').hidden=false;$('#mode').textContent=mode;$('#measurement').textContent='';measured='';const block=(title,body)=>`<section class="result-block"><h3>${title}</h3>${body}</section>`;$('#result').innerHTML=block('Tu proceso',`<p>${esc(plan.summary)}</p><p><strong>${format(answers.minutes)}</strong> por entrega · ${answers.count} ${answers.count===1?'vez':'veces'} por ${esc(answers.period)}${answers.approx?' · aproximado':''}</p>`)+block('Dónde puede ayudarte la IA',`<ol>${plan.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`)+block('Tu revisión',`<p>${esc(plan.review)}</p>`)+block('Tu primera prueba',`<p>${esc(plan.test)}</p>`)+block('Qué falta comprobar',`<ul>${plan.assumptions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>Tu ahorro aparecerá cuando registres el tiempo de la prueba.</p>`);$('#result-panel').scrollIntoView({behavior:'smooth',block:'start'})}
$('#form').addEventListener('submit',async e=>{e.preventDefault();const error=validate();if(error){$('#error').textContent=error;return}if(step<4){step++;showStep();return}answers=read();plan=localPlan(answers);let mode='PLAN GUIADO';if($('#consent').checked){if(!access){render(mode);toast('Plan guiado listo. Para Gemini, abre tu enlace privado de prueba.');return}$('#next').disabled=true;$('#next').textContent='Preparando con IA…';try{plan=await enrich(answers);mode='PLAN CON GEMINI'}catch(err){toast(err.name==='TimeoutError'?'La IA tardó demasiado. Conservamos el plan guiado.':err.message+' Conservamos el plan guiado.')}finally{$('#next').disabled=false;$('#next').textContent='Preparar mi plan'}}render(mode)});
$('#prev').onclick=()=>{if(step>0){step--;showStep()}};$('#edit').onclick=()=>{$('#result-panel').hidden=true;$('#input-panel').hidden=false;showStep();$('#input-panel').scrollIntoView({behavior:'smooth'})};$('#new').onclick=()=>{if(!confirm('¿Empezar otra tarea? Copia tu plan antes de continuar.'))return;$('#form').reset();step=0;$('#result-panel').hidden=true;$('#input-panel').hidden=false;showStep()};
$('#measure').onclick=()=>{if(!validTime($('#trial-hours'),$('#trial-minutes'))){toast('Introduce horas y minutos válidos.');return}const after=Number($('#trial-hours').value)*60+Number($('#trial-minutes').value);if(after<=0){toast('Registra un tiempo mayor que cero.');return}const delta=answers.minutes-after;const pct=Math.abs(delta/answers.minutes*100).toFixed(1);const scale=Math.max(answers.minutes,after);measured=delta>=0?`Ahorro registrado: ${format(delta)} por entrega (${pct}%). ${format(delta*answers.count)} por ${answers.period} con la frecuencia indicada.`:`La prueba tomó ${format(-delta)} más (${pct}%). Revisa dónde aumentó el tiempo antes de repetir.`;$('#measurement').innerHTML=`<div class="metric"><span>Antes</span><strong>${format(answers.minutes)}</strong></div><div class="bar" style="--width:${answers.minutes/scale*100}%"></div><div class="metric"><span>Tu prueba</span><strong>${format(after)}</strong></div><div class="bar blue" style="--width:${after/scale*100}%"></div><p>${esc(measured)}</p><p class="hint">Comparación de los tiempos que registraste${answers.approx?', con un valor inicial aproximado':''}. Una sola prueba no garantiza el mismo ahorro en todas las entregas.</p>`};
$('#copy').onclick=async()=>{const text=`SIMPLIFICA TU TRABAJO\n${plan.summary}\nTiempo actual: ${format(answers.minutes)} por entrega; ${answers.count} veces por ${answers.period}.\n\nPLAN\n${plan.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\nREVISIÓN\n${plan.review}\n\nPRUEBA\n${plan.test}\n\nSUPUESTOS\n${plan.assumptions.join('\n')}\n\n${measured}`;try{await navigator.clipboard.writeText(text);toast('Plan copiado')}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();toast(copied?'Plan copiado':'No se pudo copiar. Selecciona el texto del plan.')}};
