export function createDictation({Recognition,field,onState}){
 let recognition=null,active=false,base='',finalText='',finished=false;
 function finish(message='Puedes revisar y corregir el texto.'){active=false;finished=true;onState(false,message)}
 return {get active(){return active},start(){if(active)return;recognition=new Recognition();recognition.lang='es-CO';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;base=field.value.trim();finalText='';finished=false;active=true;onState(true,'Escuchando… pulsa Detener al terminar.');recognition.onresult=e=>{if(finished)return;let pending='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalText+=(finalText?' ':'')+text.trim();else pending+=(pending?' ':'')+text.trim()}const combined=[base,finalText,pending].filter(Boolean).join(' ');field.value=combined.slice(0,field.maxLength>0?field.maxLength:10000)};recognition.onerror=e=>{const messages={'not-allowed':'Permite usar el micrófono en tu navegador o escribe la respuesta.','service-not-allowed':'El navegador no permite el dictado. Puedes usar el micrófono del teclado.','audio-capture':'No encontramos un micrófono disponible.','no-speech':'No se escuchó una respuesta. Puedes intentarlo otra vez.','network':'El dictado necesita conexión. Puedes escribir o usar el micrófono del teclado.'};finish(messages[e.error]||'No se pudo completar el dictado. Tu texto se conserva.')};recognition.onend=()=>{if(!finished)finish()};try{recognition.start()}catch{finish('No pudimos iniciar el micrófono. Puedes escribir la respuesta.')}},stop(){if(!active)return;try{recognition.stop()}catch{finish()}},cancel(){if(!recognition||!active)return;finished=true;try{recognition.abort()}catch{}finish('Tu texto se conserva.')}}
}
export function mountDictation(root=document){
 const Recognition=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;const controllers=[];
 root.querySelectorAll('.step textarea').forEach(field=>{const controls=root.createElement('div');controls.className='voice-controls';const button=root.createElement('button');button.type='button';button.className='secondary voice-button';button.textContent='🎙 Responder con mi voz';button.setAttribute('aria-pressed','false');const state=root.createElement('p');state.className='hint';state.setAttribute('role','status');state.setAttribute('aria-live','polite');controls.append(button,state);field.after(controls);if(!Recognition){button.disabled=true;state.textContent='Este navegador no ofrece dictado. Puedes usar el micrófono del teclado del celular o escribir.';return}state.textContent='Tu voz se convierte en texto editable. No guardamos audio; el navegador puede procesarlo en línea.';const controller=createDictation({Recognition,field,onState:(active,message)=>{button.textContent=active?'■ Detener':'🎙 Responder con mi voz';button.setAttribute('aria-pressed',String(active));state.textContent=message;root.querySelector('#next').disabled=active;root.querySelectorAll('.voice-button').forEach(b=>{if(b!==button)b.disabled=active})}});controllers.push(controller);button.onclick=()=>{if(controller.active)controller.stop();else controller.start()}});
 const cancel=()=>controllers.forEach(c=>c.cancel());root.querySelector('#prev').addEventListener('click',cancel);root.querySelector('#form').addEventListener('submit',cancel,true);globalThis.addEventListener?.('pagehide',cancel);return {cancel};
}
if(typeof document!=='undefined')mountDictation();
