import{renderPage,contactURL}from './renderer.mjs';
const $=id=>document.getElementById(id);let step=0,busy=false,settings=null;const steps=[...document.querySelectorAll('.step')];let access='';try{const fragment=new URLSearchParams(location.hash.slice(1));access=fragment.get('acceso')||sessionStorage.getItem('santicorrea-demo-access')||'';if(fragment.has('acceso')){sessionStorage.setItem('santicorrea-demo-access',access);history.replaceState(null,'',location.pathname+location.search)}}catch{}
function showStep(){steps.forEach((s,i)=>s.hidden=i!==step);$('progress').textContent=`Pregunta ${step+1} de 5`;$('prev').hidden=step===0;$('next').textContent=step===4?'Crear mi página':'Siguiente';$('error').textContent=''}
function readSettings(){return Object.fromEntries(['name','project','audience','offer','difference','contact','design'].map(k=>[k,$(k).value.trim()]))}
function valid(){const required=[['name','project'],['audience'],['offer'],['difference'],[]][step];if(required.some(k=>$(k).value.trim().length<(k==='name'?2:10))){$('error').textContent='Escribe una respuesta un poco más completa para continuar.';return false}if(step===4&&$('contact').value.trim()&&!contactURL($('contact').value)){$('error').textContent='Escribe un correo válido o una dirección que empiece por https://. También puedes dejarlo vacío.';return false}return true}
$('form').onsubmit=e=>{e.preventDefault();if(busy||!valid())return;if(step<4){step++;showStep()}else generate()};$('prev').onclick=()=>{if(step>0){step--;showStep()}};
function basePage(s){return{title:s.name,subtitle:s.project,about:s.difference,services:s.offer.split(/\n+/).map(x=>x.trim()).filter(Boolean),contactText:'Hablemos de tu proyecto'}}
function data(){return{title:$('title').value,subtitle:$('subtitle').value,about:$('about').value,services:$('services').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),contactText:$('contactText').value}}
function preview(){$('preview').srcdoc=renderPage(data(),settings)}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4500)}
async function generate(){if(busy)return;busy=true;settings=readSettings();$('next').disabled=true;$('regenerate').disabled=true;$('next').textContent='Preparando…';let page=basePage(settings),mode='PÁGINA BASE · TUS RESPUESTAS';try{if($('ai').checked){if(!access)toast('La página base está lista. Usa tu enlace privado para redactar con IA.');else{const response=await fetch('https://santicorrea-contenido-api.vercel.app/api/pagina',{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Access':access},body:JSON.stringify(settings),signal:AbortSignal.timeout(105000)});if(!response.ok)throw Error();const result=await response.json();if(!['title','subtitle','about','contactText'].every(k=>typeof result[k]==='string')||!Array.isArray(result.services)||!result.services.every(s=>typeof s==='string'))throw Error();page=result;mode='TEXTOS PREPARADOS CON IA'}}}catch{toast('La IA no pudo terminar. Conservamos una página base con tus respuestas.')}finally{for(const k of ['title','subtitle','about','contactText'])$(k).value=page[k];$('services').value=page.services.join('\n');$('mode').textContent=mode;preview();$('input').hidden=true;$('result').hidden=false;busy=false;$('next').disabled=false;$('regenerate').disabled=false;showStep();$('result').scrollIntoView({behavior:'smooth',block:'start'})}}
for(const k of ['title','subtitle','about','services','contactText'])$(k).addEventListener('input',preview);
$('previewSize').onchange=()=>document.querySelector('.preview-shell').classList.toggle('desktop',$('previewSize').value==='desktop');
$('edit').onclick=()=>{if(busy)return;$('input').hidden=false;$('result').hidden=true;step=0;showStep();$('input').scrollIntoView({behavior:'smooth'})};
$('regenerate').onclick=()=>{if(confirm('Esto reemplazará los textos editados. ¿Preparar otra versión?'))generate()};
$('download').onclick=()=>{const blob=new Blob([renderPage(data(),settings)],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(settings.name.replace(/[^a-z0-9áéíóúñ_-]/gi,'-')||'Mi-proyecto')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Tu página se ha descargado.')};
$('copy').onclick=async()=>{const d=data();try{await navigator.clipboard.writeText([d.title,d.subtitle,d.about,...d.services,settings.contact].filter(Boolean).join('\n\n'));toast('Textos copiados.')}catch{toast('No pudimos copiar automáticamente. Puedes seleccionar el texto en los campos.')}};
showStep();
