export function mergeSpeechResults(results){
 const words=[];const key=w=>w.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]/gu,'');
 for(const result of results){const incoming=String(result[0]?.transcript||'').trim().split(/\s+/).filter(Boolean);if(!incoming.length)continue;let overlap=0;for(let n=Math.min(words.length,incoming.length);n>0;n--){if(words.slice(-n).every((w,i)=>key(w)===key(incoming[i]))){overlap=n;break}}words.push(...incoming.slice(overlap));}
 return words.join(' ');
}
export function createDictation({Recognition,field,onState}){
 let recognition=null,active=false,base='',finished=false,session=0,keepListening=false;
 function finish(message='Puedes revisar y corregir el texto.'){active=false;finished=true;keepListening=false;onState(false,message)}
 return {get active(){return active},start(){if(active)return;recognition=new Recognition();const run=++session;recognition.lang='es-CO';recognition.continuous=true;recognition.interimResults=false;recognition.maxAlternatives=1;base=field.value.trim();finished=false;keepListening=true;active=true;onState(true,'Escuchando… pulsa Detener al terminar.');recognition.onresult=e=>{if(finished||run!==session)return;const combined=[base,mergeSpeechResults(Array.from(e.results))].filter(Boolean).join(' ');field.value=combined.slice(0,field.maxLength>0?field.maxLength:10000)};recognition.onerror=e=>{if(run!==session)return;const messages={'not-allowed':'Permite usar el micrófono en tu navegador o escribe la respuesta.','service-not-allowed':'El navegador no permite el dictado. Puedes usar el micrófono del teclado.','audio-capture':'No encontramos un micrófono disponible.','no-speech':'No se escuchó una respuesta. Puedes intentarlo otra vez.','network':'El dictado necesita conexión. Puedes escribir o usar el micrófono del teclado.'};finish(messages[e.error]||'No se pudo completar el dictado. Tu texto se conserva.')};recognition.onend=()=>{if(finished||run!==session)return;if(!keepListening){finish();return}base=field.value.trim();const current=recognition;setTimeout(()=>{if(!active||finished||!keepListening||run!==session)return;try{current.start()}catch{finish('El micrófono se detuvo. Tu texto se conserva; puedes retomarlo.')}},250)};try{recognition.start()}catch{finish('No pudimos iniciar el micrófono. Puedes escribir la respuesta.')}},stop(){if(!active)return;keepListening=false;const stoppingSession=session;try{recognition.stop()}catch{finish()}setTimeout(()=>{if(active&&!keepListening&&session===stoppingSession)finish()},800)},cancel(){if(!recognition||!active)return;finished=true;keepListening=false;try{recognition.abort()}catch{}finish('Tu texto se conserva.')}}
}
export function mountDictation(root=document){
 const Recognition=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;const controllers=[];
 root.querySelectorAll('.step textarea').forEach(field=>{const controls=root.createElement('div');controls.className='voice-controls';const button=root.createElement('button');button.type='button';button.className='secondary voice-button';button.textContent='🎙 Responder con mi voz';button.setAttribute('aria-pressed','false');const state=root.createElement('p');state.className='hint';state.setAttribute('role','status');state.setAttribute('aria-live','polite');controls.append(button,state);field.after(controls);if(!Recognition){button.disabled=true;state.textContent='Este navegador no ofrece dictado. Puedes usar el micrófono del teclado del celular o escribir.';return}state.textContent='Tu voz se convierte en texto editable. No guardamos audio; el navegador puede procesarlo en línea.';const controller=createDictation({Recognition,field,onState:(active,message)=>{button.textContent=active?'■ Detener':'🎙 Responder con mi voz';button.setAttribute('aria-pressed',String(active));state.textContent=message;root.querySelector('#next').disabled=active;root.querySelectorAll('.voice-button').forEach(b=>{if(b!==button)b.disabled=active})}});controllers.push(controller);button.onclick=()=>{if(controller.active)controller.stop();else controller.start()}});
 const cancel=()=>controllers.forEach(c=>c.cancel());root.querySelector('#prev').addEventListener('click',cancel);root.querySelector('#form').addEventListener('submit',cancel,true);globalThis.addEventListener?.('pagehide',cancel);return {cancel};
}
if(typeof document!=='undefined')mountDictation();
